"""initial lumen schema

Revision ID: 31042c48661c
Revises: 
Create Date: 2026-09-07 01:06:14.875785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31042c48661c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('provider_key', sa.String(length=64), nullable=True),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=False)
    op.create_index(op.f('ix_instruments_provider_key'), 'instruments', ['provider_key'], unique=False)
    op.create_index(op.f('ix_instruments_sector'), 'instruments', ['sector'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('market_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_calendar'))
    )
    op.create_index(op.f('ix_market_calendar_calendar_date'), 'market_calendar', ['calendar_date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('picture_url', sa.String(length=1000), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_app_open_at', sa.DateTime(), nullable=True),
    sa.Column('previous_visit_at', sa.DateTime(), nullable=True),
    sa.Column('last_digest_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_observation_seen_at', sa.DateTime(), nullable=True),
    sa.Column('manual_baseline_at', sa.DateTime(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('instrument_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('typical_daily_move', sa.Float(), nullable=True),
    sa.Column('typical_move_sample_days', sa.Integer(), nullable=False),
    sa.Column('historical_volatility', sa.Float(), nullable=True),
    sa.Column('volatility_sample_days', sa.Integer(), nullable=False),
    sa.Column('average_volume', sa.Float(), nullable=True),
    sa.Column('historical_gap_stdev', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_instrument_daily_stats_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument_daily_stats')),
    sa.UniqueConstraint('instrument_id', 'as_of_date', name='uq_daily_stats')
    )
    op.create_index(op.f('ix_instrument_daily_stats_instrument_id'), 'instrument_daily_stats', ['instrument_id'], unique=False)
    op.create_table('intraday_volume_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('minute_of_session', sa.Integer(), nullable=False),
    sa.Column('average_volume', sa.Float(), nullable=False),
    sa.Column('sample_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_intraday_volume_baselines_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intraday_volume_baselines')),
    sa.UniqueConstraint('instrument_id', 'minute_of_session', name='uq_intraday_volume')
    )
    op.create_index(op.f('ix_intraday_volume_baselines_instrument_id'), 'intraday_volume_baselines', ['instrument_id'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('peak_score', sa.Float(), nullable=False),
    sa.Column('objective_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('deterministic_explanation', sa.Text(), nullable=False),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('is_market_wide', sa.Boolean(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('supporting_signals', sa.JSON(), nullable=True),
    sa.Column('confidence_report', sa.JSON(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('is_replay', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_market_events_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_events')),
    sa.UniqueConstraint('event_key', 'scope', name='uq_event_key_scope')
    )
    op.create_index('ix_event_instrument_updated', 'market_events', ['instrument_id', 'last_updated_at'], unique=False)
    op.create_index('ix_event_scope_score', 'market_events', ['scope', 'current_score'], unique=False)
    op.create_index(op.f('ix_market_events_event_key'), 'market_events', ['event_key'], unique=False)
    op.create_index(op.f('ix_market_events_last_updated_at'), 'market_events', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_market_events_session_date'), 'market_events', ['session_date'], unique=False)
    op.create_index(op.f('ix_market_events_status'), 'market_events', ['status'], unique=False)
    op.create_table('market_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('freshness', sa.String(length=16), nullable=False),
    sa.Column('is_replay', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('previous_price', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('gap_percent', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('sector_return', sa.Float(), nullable=True),
    sa.Column('intraday_volatility', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_market_observations_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_observations'))
    )
    op.create_index(op.f('ix_market_observations_session_date'), 'market_observations', ['session_date'], unique=False)
    op.create_index('ix_observation_instrument_time', 'market_observations', ['instrument_id', 'observed_at'], unique=False)
    op.create_index('ix_observation_scope_time', 'market_observations', ['scope', 'observed_at'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('causal_link_established', sa.Boolean(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('is_replay', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_news_items_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_items'))
    )
    op.create_index('ix_news_instrument_time', 'news_items', ['instrument_id', 'published_at'], unique=False)
    op.create_table('replay_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scenario_key', sa.String(length=64), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('virtual_start', sa.DateTime(), nullable=False),
    sa.Column('virtual_now', sa.DateTime(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_replay_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replay_sessions'))
    )
    op.create_index(op.f('ix_replay_sessions_scenario_key'), 'replay_sessions', ['scenario_key'], unique=False)
    op.create_table('stock_mutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_stock_mutes_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_mutes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_mutes')),
    sa.UniqueConstraint('user_id', 'instrument_id', name='uq_user_mute')
    )
    op.create_index(op.f('ix_stock_mutes_instrument_id'), 'stock_mutes', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_stock_mutes_user_id'), 'stock_mutes', ['user_id'], unique=False)
    op.create_table('user_instrument_affinity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('why_count', sa.Integer(), nullable=False),
    sa.Column('dismiss_count', sa.Integer(), nullable=False),
    sa.Column('more_like_this_count', sa.Integer(), nullable=False),
    sa.Column('mute_count', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_user_instrument_affinity_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_instrument_affinity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_instrument_affinity')),
    sa.UniqueConstraint('user_id', 'instrument_id', name='uq_user_instrument')
    )
    op.create_index(op.f('ix_user_instrument_affinity_instrument_id'), 'user_instrument_affinity', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_user_instrument_affinity_user_id'), 'user_instrument_affinity', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_appetite', sa.String(length=20), nullable=True),
    sa.Column('investment_style', sa.String(length=30), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('user_sector_affinity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sector_affinity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sector_affinity')),
    sa.UniqueConstraint('user_id', 'sector', name='uq_user_sector')
    )
    op.create_index(op.f('ix_user_sector_affinity_user_id'), 'user_sector_affinity', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('event_timeline_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], name=op.f('fk_event_timeline_points_event_id_market_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_timeline_points'))
    )
    op.create_index(op.f('ix_event_timeline_points_event_id'), 'event_timeline_points', ['event_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], name=op.f('fk_notifications_event_id_market_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_notification_user_event')
    )
    op.create_index('ix_notification_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('user_event_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('why_opened_count', sa.Integer(), nullable=False),
    sa.Column('breakdown_opened_count', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], name=op.f('fk_user_event_states_event_id_market_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_event_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_event_states')),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event')
    )
    op.create_index(op.f('ix_user_event_states_event_id'), 'user_event_states', ['event_id'], unique=False)
    op.create_index(op.f('ix_user_event_states_user_id'), 'user_event_states', ['user_id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], name=op.f('fk_user_interactions_event_id_market_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_user_interactions_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_interactions'))
    )
    op.create_index('ix_interaction_user_time', 'user_interactions', ['user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_user_interactions_event_id'), 'user_interactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_instrument_id'), 'user_interactions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_kind'), 'user_interactions', ['kind'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_watchlist_items_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_item')
    )
    op.create_index(op.f('ix_watchlist_items_instrument_id'), 'watchlist_items', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_instrument_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_user_interactions_kind'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_instrument_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_event_id'), table_name='user_interactions')
    op.drop_index('ix_interaction_user_time', table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_user_event_states_user_id'), table_name='user_event_states')
    op.drop_index(op.f('ix_user_event_states_event_id'), table_name='user_event_states')
    op.drop_table('user_event_states')
    op.drop_index('ix_notification_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_event_timeline_points_event_id'), table_name='event_timeline_points')
    op.drop_table('event_timeline_points')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_user_sector_affinity_user_id'), table_name='user_sector_affinity')
    op.drop_table('user_sector_affinity')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_instrument_affinity_user_id'), table_name='user_instrument_affinity')
    op.drop_index(op.f('ix_user_instrument_affinity_instrument_id'), table_name='user_instrument_affinity')
    op.drop_table('user_instrument_affinity')
    op.drop_index(op.f('ix_stock_mutes_user_id'), table_name='stock_mutes')
    op.drop_index(op.f('ix_stock_mutes_instrument_id'), table_name='stock_mutes')
    op.drop_table('stock_mutes')
    op.drop_index(op.f('ix_replay_sessions_scenario_key'), table_name='replay_sessions')
    op.drop_table('replay_sessions')
    op.drop_index('ix_news_instrument_time', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_observation_scope_time', table_name='market_observations')
    op.drop_index('ix_observation_instrument_time', table_name='market_observations')
    op.drop_index(op.f('ix_market_observations_session_date'), table_name='market_observations')
    op.drop_table('market_observations')
    op.drop_index(op.f('ix_market_events_status'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_session_date'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_last_updated_at'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_event_key'), table_name='market_events')
    op.drop_index('ix_event_scope_score', table_name='market_events')
    op.drop_index('ix_event_instrument_updated', table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_intraday_volume_baselines_instrument_id'), table_name='intraday_volume_baselines')
    op.drop_table('intraday_volume_baselines')
    op.drop_index(op.f('ix_instrument_daily_stats_instrument_id'), table_name='instrument_daily_stats')
    op.drop_table('instrument_daily_stats')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_calendar_calendar_date'), table_name='market_calendar')
    op.drop_table('market_calendar')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_sector'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_provider_key'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
